version: "3.8"
services: 
    monEtab-postgresql: 
        image: postgres:latest
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432